
- name: Upgrade packages
  hosts: localhost
  gather_facts: false
  become: true
  tasks:
    - name: upgrade docker containers
      community.docker.docker_compose:
        project_src: /root/compose
        pull: true
        state: present
    - name: upgrade packages
       community.general.apk:
        update_cache: true
        upgrade: true

