
- name: Update repositories and upgrade all packages ...TEST
  hosts: localhost
  become: true
  tasks:
     - name: do it
       community.general.apk:
       update_cache: true
       upgrade: true
  